### ISSUE TITLE
[BUG] Linking fails on macOS 15 arm64 with Xcode 16.4

### ISSUE THREAD

**Issue by eithe** [software-mansion/rnrepo#290]
### 📋 Description

Hi and thanks for creating this!

When building for iOS in our ci/cd pipeline with macOS 15 and Xcode 16.4 I get the following error during the linking process. Please note that building locally (macOS 26, Xcode 26.2) works.

```
...
▸ Compiling MyApp_vers.c
▸ Compiling MapBridge.m
▸ Linking MyApp
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
⚠️  ld: Could not find or use auto-linked framework 'UIUtilities': framework 'UIUtilities' not found
⚠️  ld: Could not find or use auto-linked framework '_LocationEssentials': framework '_LocationEssentials' not found
⚠️  ld: Could not parse or use implicit file '/Applications/Xcode_16.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it

❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


** ARCHIVE FAILED **
```

Any suggestions on what I can try? Unfortunately Azure Devops does not yet include build agents with macOS 26.

### 🔄 Steps to Reproduce

Setup the project as per the guide, and try to build on macOS 15 Xcode 16.4

`/usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace ./MyApp.xcworkspace -scheme Release clean archive`

### 🤔 Expected Behavior

It should build

### 😲 Actual Behavior

Build fails

### RNRepo version (and/or @rnrepo/expo-config-plugin version)

0.3.0

### React Native version

0.81.5

### Gradle version

8.14.3

### Operating System

macOS 15

**Comment by ShaneJMitchell** [comment]
> > Hi, At the moment, we’re focusing on supporting the latest version of Xcode.
> 
> Thanks and no worries, I will update this post once [Azure Devops decides to add macos-26 build agents](https://github.com/microsoft/azure-pipelines-agent/issues/5455).

is there any sort of update on this?
The referenced ticket was created 2 months ago and hasn't had a single update or even a comment recognizing the issue and stating it's prioritization or expected ETA.
There are tons of people that use Azure MS-hosted agents for their support of building and maintaining mobile apps - Microsoft is very close to a bunch of customers jumping ship from Azure DevOps if we all have to buy a fleet of Macs just to do our app builds - at that point we can just use Jenkins and save a ton of $.
